### ISSUE TITLE
🐛 |  Run junit test in // with launcher results on failure

### ISSUE THREAD

**Issue by iguissouma** [chutney-testing/chutney-kotlin-dsl#55]
I have the following stacktrace while executing a junit Test in // with Launcher

```
java.io.UncheckedIOException: Unable to write in directory: C:\dev\workspace\libs\chutney\.chutney\environment

	at com.chutneytesting.tools.file.FileUtils.initFolder(FileUtils.java:34)
	at com.chutneytesting.environment.infra.JsonFilesEnvironmentRepository.<init>(JsonFilesEnvironmentRepository.java:36)
	at com.chutneytesting.kotlin.execution.ExecutionService.<init>(ExecutionService.kt:27)
	at com.chutneytesting.kotlin.launcher.Launcher.<init>(Launcher.kt:20)
	at com.chutneytesting.kotlin.launcher.Launcher.<init>(Launcher.kt:17)
```

**Comment by boddissattva** [comment]
Resolve with https://github.com/chutney-testing/chutney/issues/746
